In [40]:
import pandas as pd
import argparse
import numpy as np

In [41]:
df=pd.read_csv("C:/Users/Swarupa/Desktop/Terrorism.csv")

C:\Users\Swarupa\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (4,6,31,33,53,61,62,63,76,79,90,92,94,96,114,115,121) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [42]:
df.head()

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,197000000001,1970,7,2,NaN,0,NaN,58,Dominican Republic,2,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
1,197000000002,1970,0,0,NaN,0,NaN,130,Mexico,1,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
2,197001000001,1970,1,0,NaN,0,NaN,160,Philippines,5,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
3,197001000002,1970,1,0,NaN,0,NaN,78,Greece,8,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
4,197001000003,1970,1,0,NaN,0,NaN,101,Japan,4,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN

In [43]:
df = df[df.imonth != 0]
df = df[df.iday != 0]

In [44]:
del df["approxdate"]

In [45]:
df['extended'].replace(0, 'No',inplace=True)
df['extended'].replace(1, 'Yes',inplace=True)

In [46]:
df=df.fillna("None")

In [47]:
df.head()

,eventid,iyear,imonth,iday,extended,resolution,country,country_txt,region,region_txt,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,197000000001,1970,7,2,No,None,58,Dominican Republic,2,Central America & Caribbean,...,None,None,None,None,PGIS,0,0,0,0,None
5,197001010002,1970,1,1,No,None,217,United States,1,North America,...,"The Cairo Chief of Police, William Petersen, r...","""Police Chief Quits,"" Washington Post, January...","""Cairo Police Chief Quits; Decries Local 'Mili...","Christopher Hewitt, ""Political Violence and Te...",Hewitt Project,-9,-9,0,-9,None
6,197001020001,1970,1,2,No,None,218,Uruguay,3,South America,...,None,None,None,None,PGIS,0,0,0,0,None
7,197001020002,1970,1,2,No,None,217,United States,1,North America,...,"Damages were estimated to be between $20,000-$...",Committee on Government Operations United Stat...,"Christopher Hewitt, ""Political Violence and Te...",None,Hewitt Project,-9,-9,0,-9,None
8,197001020003,1970,1,2,No,None,217,United States,1,North America,...,The New Years Gang issue a communiquÃ© to a loc...,"Tom Bates, ""Rads: The 1970 Bombing of the Army...","David Newman, Sandra Sutherland, and Jon Stewa...","The Wisconsin Cartographers' Guild, ""Wisconsin...",Hewitt Project,0,0,0,0,None

In [48]:
df['crit1'].replace(0, 'No',inplace=True)
df['crit1'].replace(1, 'Yes',inplace=True)
df['crit2'].replace(0, 'No',inplace=True)
df['crit2'].replace(1, 'Yes',inplace=True)
df['crit3'].replace(0, 'No',inplace=True)
df['crit3'].replace(1, 'Yes',inplace=True)

In [49]:
df['doubtterr'].replace(0, 'No',inplace=True)
df['doubtterr'].replace(1, 'Yes',inplace=True)
df['doubtterr'].replace(-9, 'Unknown',inplace=True)

In [50]:
df['multiple'].replace(0, 'No',inplace=True)
df['multiple'].replace(1, 'Yes',inplace=True)

In [51]:
df['vicinity'].replace(0, 'No',inplace=True)
df['vicinity'].replace(1, 'Yes',inplace=True)

In [52]:
df['success'].replace(0, 'No',inplace=True)
df['success'].replace(1, 'Yes',inplace=True)

In [53]:
df['suicide'].replace(0, 'No',inplace=True)
df['suicide'].replace(1, 'Yes',inplace=True)

In [54]:
df['guncertain1'].replace(0, 'No',inplace=True)
df['guncertain1'].replace(1, 'Yes',inplace=True)
df['guncertain2'].replace(0, 'No',inplace=True)
df['guncertain2'].replace(1, 'Yes',inplace=True)
df['guncertain3'].replace(0, 'No',inplace=True)
df['guncertain3'].replace(1, 'Yes',inplace=True)

In [55]:
df['claimed'].replace(0, 'No',inplace=True)
df['claimed'].replace(1, 'Yes',inplace=True)
df['claimed'].replace(-99, 'Unknown',inplace=True)

In [56]:
df['compclaim'].replace(0, 'No',inplace=True)
df['compclaim'].replace(1, 'Yes',inplace=True)
df['compclaim'].replace(-9, 'Unknown',inplace=True)

In [57]:
df['claim2'].replace(0, 'No',inplace=True)
df['claim2'].replace(1, 'Yes',inplace=True)

In [58]:
df['claimmode2'].replace(1, 'Letter',inplace=True)
df['claimmode2'].replace(2, 'Call(post-incident)',inplace=True)
df['claimmode2'].replace(3, 'Call(pre-incident)',inplace=True)
df['claimmode2'].replace(4, 'E-mail',inplace=True)
df['claimmode2'].replace(5, 'Note left at scene',inplace=True)
df['claimmode2'].replace(6, 'Video',inplace=True)
df['claimmode2'].replace(7, 'Posted to website, blog, social media',inplace=True)
df['claimmode2'].replace(8, 'Personal claim',inplace=True)
df['claimmode2'].replace(9, 'Other',inplace=True)
df['claimmode2'].replace(10, 'Unknown',inplace=True)

In [59]:
df['claim3'].replace(0, 'No',inplace=True)
df['claim3'].replace(1, 'Yes',inplace=True)

In [60]:
df['claimmode3'].replace(1, 'Letter',inplace=True)
df['claimmode3'].replace(2, 'Call(post-incident)',inplace=True)
df['claimmode3'].replace(3, 'Call(pre-incident)',inplace=True)
df['claimmode3'].replace(4, 'E-mail',inplace=True)
df['claimmode3'].replace(5, 'Note left at scene',inplace=True)
df['claimmode3'].replace(6, 'Video',inplace=True)
df['claimmode3'].replace(7, 'Posted to website, blog, social media',inplace=True)
df['claimmode3'].replace(8, 'Personal claim',inplace=True)
df['claimmode3'].replace(9, 'Other',inplace=True)
df['claimmode3'].replace(10, 'Unknown',inplace=True)

In [61]:
df['property'].replace(0, 'No',inplace=True)
df['property'].replace(1, 'Yes',inplace=True)
df['property'].replace(-9, 'Unknown',inplace=True)

In [62]:
df['ishostkid'].replace(0, 'No',inplace=True)
df['ishostkid'].replace(1, 'Yes',inplace=True)
df['ishostkid'].replace(-9, 'Unknown',inplace=True)

In [63]:
df['ransom'].replace(0, 'No',inplace=True)
df['ransom'].replace(1, 'Yes',inplace=True)
df['ransom'].replace(-9, 'Unknown',inplace=True)

In [64]:
df['INT_LOG'].replace(0, 'No',inplace=True)
df['INT_LOG'].replace(1, 'Yes',inplace=True)
df['INT_LOG'].replace(-9, 'Unknown',inplace=True)

In [65]:
df['INT_IDEO'].replace(0, 'No',inplace=True)
df['INT_IDEO'].replace(1, 'Yes',inplace=True)
df['INT_IDEO'].replace(-9, 'Unknown',inplace=True)

In [66]:
df['INT_MISC'].replace(0, 'No',inplace=True)
df['INT_MISC'].replace(1, 'Yes',inplace=True)
df['INT_MISC'].replace(-9, 'Unknown',inplace=True)

In [67]:
df['INT_ANY'].replace(0, 'No',inplace=True)
df['INT_ANY'].replace(1, 'Yes',inplace=True)
df['INT_ANY'].replace(-9, 'Unknown',inplace=True)

In [68]:
del df["country"]
del df["claimmode"]
del df["propextent"]
del df["natlty3"]
del df["targsubtype3"]
del df["targtype3"]
del df["natlty2"]
del df["targsubtype2"]
del df["targtype2"]
del df["natlty1"]
del df["targsubtype1"]
del df["targtype1"]
del df["weapsubtype4"]
del df["weaptype4"]
del df["weapsubtype3"]
del df["weaptype3"]
del df["weapsubtype2"]
del df["weaptype2"]
del df["weapsubtype1"]
del df["weaptype1"]
del df["attacktype3"]
del df["attacktype2"]
del df["attacktype1"]
del df["region"]
del df["alternative"]
del df["specificity"]

In [69]:
df2=["individual","nperps","nperpcap","nkill","nkillus","nkillter","nwound","nwoundus","nwoundte","propvalue","nhostkid","nhostkidus","nhours","ndays","ransomamt","ransomamtus","ransompaid","ransompaidus","nreleased"]

In [70]:
df5=df[df.columns.difference(df2)]

In [71]:
df.head()

,eventid,iyear,imonth,iday,extended,resolution,country_txt,region_txt,provstate,city,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,197000000001,1970,7,2,No,None,Dominican Republic,Central America & Caribbean,None,Santo Domingo,...,None,None,None,None,PGIS,No,No,No,No,None
5,197001010002,1970,1,1,No,None,United States,North America,Illinois,Cairo,...,"The Cairo Chief of Police, William Petersen, r...","""Police Chief Quits,"" Washington Post, January...","""Cairo Police Chief Quits; Decries Local 'Mili...","Christopher Hewitt, ""Political Violence and Te...",Hewitt Project,Unknown,Unknown,No,Unknown,None
6,197001020001,1970,1,2,No,None,Uruguay,South America,Montevideo,Montevideo,...,None,None,None,None,PGIS,No,No,No,No,None
7,197001020002,1970,1,2,No,None,United States,North America,California,Oakland,...,"Damages were estimated to be between $20,000-$...",Committee on Government Operations United Stat...,"Christopher Hewitt, ""Political Violence and Te...",None,Hewitt Project,Unknown,Unknown,No,Unknown,None
8,197001020003,1970,1,2,No,None,United States,North America,Wisconsin,Madison,...,The New Years Gang issue a communiquÃ© to a loc...,"Tom Bates, ""Rads: The 1970 Bombing of the Army...","David Newman, Sandra Sutherland, and Jon Stewa...","The Wisconsin Cartographers' Guild, ""Wisconsin...",Hewitt Project,No,No,No,No,None

In [72]:
df5.head()

,INT_ANY,INT_IDEO,INT_LOG,INT_MISC,addnotes,alternative_txt,attacktype1_txt,attacktype2_txt,attacktype3_txt,city,...,vicinity,weapdetail,weapsubtype1_txt,weapsubtype2_txt,weapsubtype3_txt,weapsubtype4_txt,weaptype1_txt,weaptype2_txt,weaptype3_txt,weaptype4_txt
0,No,No,No,No,None,None,Assassination,None,None,Santo Domingo,...,No,None,None,None,None,None,Unknown,None,None,None
5,Unknown,Unknown,Unknown,No,"The Cairo Chief of Police, William Petersen, r...",None,Armed Assault,None,None,Cairo,...,No,Several gunshots were fired.,Unknown Gun Type,None,None,None,Firearms,None,None,None
6,No,No,No,No,None,None,Assassination,None,None,Montevideo,...,No,Automatic firearm,Automatic Weapon,None,None,None,Firearms,None,None,None
7,Unknown,Unknown,Unknown,No,"Damages were estimated to be between $20,000-$...",Other Crime Type,Bombing/Explosion,None,None,Oakland,...,No,None,Unknown Explosive Type,None,None,None,Explosives/Bombs/Dynamite,None,None,None
8,No,No,No,No,The New Years Gang issue a communiquÃ© to a loc...,None,Facility/Infrastructure Attack,None,None,Madison,...,No,Firebomb consisting of gasoline,Molotov Cocktail/Petrol Bomb,None,None,None,Incendiary,None,None,None

In [73]:
df4=df[['eventid','iyear','imonth','iday',"individual","nperps","nperpcap","nkill","nkillus","nkillter","nwound","nwoundus","nwoundte","propvalue","nhostkid","nhostkidus","nhours","ndays","ransomamt","ransomamtus","ransompaid","ransompaidus","nreleased"]]
df4.replace('None', 0 ,inplace=True)

C:\Users\Swarupa\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [80]:
new_df = pd.merge(df4, df5,  how='left', left_on=['eventid','iyear','imonth','iday'],right_on=['eventid','iyear','imonth','iday'])

In [81]:
new_df.to_csv("Terrorism_cleaned.csv", encoding='utf-8',index=False)

In [82]:
new_df.head()

,eventid,iyear,imonth,iday,individual,nperps,nperpcap,nkill,nkillus,nkillter,...,vicinity,weapdetail,weapsubtype1_txt,weapsubtype2_txt,weapsubtype3_txt,weapsubtype4_txt,weaptype1_txt,weaptype2_txt,weaptype3_txt,weaptype4_txt
0,197000000001,1970,7,2,0,0.0,0.0,1.0,0.0,0.0,...,No,None,None,None,None,None,Unknown,None,None,None
1,197001010002,1970,1,1,0,-99.0,-99.0,0.0,0.0,0.0,...,No,Several gunshots were fired.,Unknown Gun Type,None,None,None,Firearms,None,None,None
2,197001020001,1970,1,2,0,3.0,0.0,0.0,0.0,0.0,...,No,Automatic firearm,Automatic Weapon,None,None,None,Firearms,None,None,None
3,197001020002,1970,1,2,0,-99.0,-99.0,0.0,0.0,0.0,...,No,None,Unknown Explosive Type,None,None,None,Explosives/Bombs/Dynamite,None,None,None
4,197001020003,1970,1,2,0,1.0,1.0,0.0,0.0,0.0,...,No,Firebomb consisting of gasoline,Molotov Cocktail/Petrol Bomb,None,None,None,Incendiary,None,None,None

In [83]:
new_df.shape

(169459, 108)

In [84]:
df.shape

(169459, 108)